version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5155:3000"
    command: npm run dev
    restart: always
    volumes:
      - .:/usr/app
    environment:
      - NODE_ENV=development
